language: scala
jdk: oraclejdk8
sudo: false
before_install: umask 0022
scala: 2.10.6
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_script:
- git config --global user.name "Travis CI"
-  git config --global user.email "riomus@gmail.com"
script:
- sbt clean coverage test && sbt coverageAggregate
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- sbt coveralls
- sbt unidoc && sbt ghpages-push-site
env:
  global:
  - SBT_GHPAGES_COMMIT_MESSAGE='[ci skip] page update'
  - secure: C2heW4+NDn5YLMVkHj8BVL+ixuBI2sufJGidiIxHTdBfq1Gf0bJGTKyLMvAKoQfuuPaUTpxFSx5JlVdhaSEfK06JFMDBTYTh2mkAYgFTQLJRU8d7NZ07vECsXwaHk56ZP0BLGpdvXp8kWutEYl7pZJKYzQwVzItrKYQcQ+rZX8ZX1Tyz7LTh4X6291XkwuoWRL4rC3xecFGvONyDdphowetRNWUe067wsbXXmeRzdcaptR54kBnfJkdJzCyhPPThCc/fnOJtL1DpEcMrMSgEMaJLEF8xdSR+BpLg2NCOJ+QPQrfsJErrbh3Lq1mf2EV60JJPh56Fl7w9YXMsBdss+lbkAmn53e4vQ7t1SIfhuYAl6+CUE3TN/nzUKHqi06S5YC8XIReh6K4zWRGlE4CXajvPznWDqTv5kRLRDiRh41wKMfXmk//iwDK34EaRZ+SWFdO4ltPmC/VI0wutfNm+b5hz1G4V/KUX5vJ6AULLCcIuSIXt1bWuBMMvwssd7PtQDKubKTlnoL0Dv9zl9ceQ+JdGV5kISGY6KOz7HTHUnFTeQ4tIhCrnrLKmbk3IAo+wQMPr+1uzmTXYQSJ7++/C07msMx0x+K5VyWcoAwo6RttGzDbDbFcRn86OhS9lxUp9K8Zp3STW3lHjGmf+fS7U9w6ZCTYH9n8f+TcysPt46rk=
  - secure: k4YVa5vrLNyeBzcTzJJyzjt3fTgpwzL7OuVb+/1jNEBflaOfvrkFDbQiz3i7KgC/Oq04hhLM5N0ryJow01AM1pCJF6gEyXFbF7EirsVSbhTyH1euDCQiTlw4vaCQDMB0OXZ7vPQuAe91UikgSwqR2pugSVLomEqW08d7rXtSu5KhrjjLC9d4mB0vWLenFF7FQCB7CITEsWHN3PbfNmFE4p12qNzMcjAY5kcZOR2gXDPdBXjv3eTXj8vG9Edp/1zGMGteBMIhisH2VWGHqAf/Jil7+dHsaoj6HvsMhoPNoIwY06OMZKjKz19gUoLb7aF/sredBNaMLAGVUzov8wtWz0P3MB/E5kLJOOrfFoXgfZEEM3bTyccbqPnOklKy0xotsxXU0aba9EIpdF7qkT366iXIQqznBYfLwCv9LQdGyI8pszA/sMoSyV++oX36sZkxAnS9G0UqeyvDXqpoxXxccjAey6yJihtcVOjDvajDGflHkLp7L4X/TQpuk+oWGzfKO5XOiP8MBUN9X8n23PMomID794mkQL4GZjfjqHoGqc3V3aVL6E6YoHB5eVLX2zgPp3k8nTxDfEw0ZmXjnHs4ox0xA+VGnEjNTDMq8FS8PCVGXiQO7NnVsCz64K9vwMbQ+2I5N2Xl9Ge+nhh2/9hY6sofPcV8oaj+iNu7pN/tuco=
  - secure: o5jczOLJvKKc35IyOnZlHGzIMWi3GRNfHsHbB7iK4EAok1WH85VyTkcvoIl9UCVqF8cfBplTcRnr0HMzc6S8QsG3WyUbB4M9l7llJ2xlXXVk8GG5saQqSUfyxtrBQRzpHanqGtdyPGVNwJ60rqUHLbdqby4tUOnyKE6QqGkdfG1NwAuIxhzDPBLuEG+Dqp7GtgrT2NfxioaRZRld0Ybv94zkHOMHN6KcctLvZqid7mhflg2VXHZF/dOdhnRbn5WlTVRLTIfbGSFj+zNBa6EC8bWVOXC9is3/58fnFjwd8E2rdOPQbode5D9V9PHl/Das8v+QewesAhZy2T8qWcRVL686y1iEWImZwQJclIVBUgwb40RdMNCF/tFP9XIfUpYKB8toOpdPJBwQFQqfsBq7x5x77U3/G9f+j49BWYhUZBu8m1P4CxOs/Wsea93YPuvX6eHzdoH2PErhJNzW4bUs5pJ1clyd9Bw/O16X88kCtiq//rlYZPxDsMlWyxNEmpEfpcfxG8d7lbnLYGffN+nLIXZqy4nSu+53eGCJbNccqSPXQI71Fm1jIMwmJma4v2+YmSo8W/nU3jIv1LCvPb0YvaaNzTPdVqDM4e1sxVWk1Qwdb9NsZd5/o/C5apxcnj92KH4PLTdBk7vKcyTApojboB+4UnYMtVR55QESqOFIbT4=
